#!/usr/bin/env node
"use strict";

/**
 * The `.llm` harness: validation, index generation, and agent-visible skill mirrors.
 *
 *   node scripts/llm/harness.js index      Regenerate .llm/index.json, .llm/index.md, mirrors
 *   node scripts/llm/harness.js validate   Check Agent Skills conformance and line limits
 *   node scripts/llm/harness.js check      validate + fail on any stale generated artifact
 *
 * `.llm/skills/<name>/SKILL.md` is the single source of truth. Claude Code reads `.claude/skills/`,
 * Codex reads `.agents/skills/`, and Copilot reads both, so each skill is mirrored into those two
 * locations as a thin pointer rather than duplicated. See the note on `layout()` for why both
 * mirror roots are kept even though Copilot then sees each skill twice.
 */

const fs = require("fs");
const path = require("path");
const YAML = require("yaml");

const REPO_ROOT = path.resolve(__dirname, "..", "..");

/**
 * Filesystem layout, resolved per call so `DX_LLM_ROOT` can retarget the whole harness at a
 * fixture tree. That override exists only for tests, in the style of `DX_SKILLS_DIR` in
 * `scripts/update-llms-txt.js`: the rules are exercised by driving the real code over temporary
 * directories rather than by re-implementing them in assertions.
 *
 * Both mirror roots are required. Claude Code discovers only `.claude/skills/`, Codex discovers
 * only `.agents/skills/`, so dropping either breaks that client. VS Code Copilot reads both, and
 * therefore sees every skill twice; that duplication is a consequence of the standard's discovery
 * rules, not a defect to collapse. Publishing to a single root (for example `.github/skills/`)
 * would de-duplicate Copilot at the cost of breaking Claude Code and Codex.
 */
function layout() {
  const root = process.env.DX_LLM_ROOT ? path.resolve(process.env.DX_LLM_ROOT) : REPO_ROOT;
  const llmDir = path.join(root, ".llm");
  return {
    root,
    llmDir,
    skillsDir: path.join(llmDir, "skills"),
    contextFile: path.join(llmDir, "context.md"),
    indexMd: path.join(llmDir, "index.md"),
    indexJson: path.join(llmDir, "index.json"),
    mirrorRoots: [path.join(root, ".claude", "skills"), path.join(root, ".agents", "skills")],
  };
}

const BLOCK_START = "<!-- BEGIN GENERATED SKILL REGISTRY -->";
const BLOCK_END = "<!-- END GENERATED SKILL REGISTRY -->";

// Every file this harness writes carries this marker. Reaping is scoped to files that carry it so
// a hand-authored `.claude/skills/<name>/SKILL.md` is never deleted or reported as drift.
const GENERATED_MARKER = "Generated by `npm run llm:index`";

// Lines-per-file limits. `SKILL.md` is what an agent loads whole on activation, so it is capped
// hard; overflow belongs in `references/`, which are loaded only on demand. The Agent Skills spec
// applies its 500-line guidance to `SKILL.md` itself; the 500-line reference ceiling below is this
// repository's own convention. Bundled `scripts/` and `assets/` are explicitly sanctioned by the
// spec and carry no line limit here.
const LIMITS = {
  skillWarn: 150,
  skillFail: 200,
  referenceFail: 500,
  contextFail: 300,
  lineLength: 2000,
};

const NAME_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// Required and optional keys from https://agentskills.io/specification, plus the client extensions
// Claude Code and VS Code document. Anything else belongs under `metadata`.
const REQUIRED_KEYS = ["name", "description"];
const SPEC_KEYS = ["name", "description", "license", "compatibility", "metadata", "allowed-tools"];
const CLIENT_EXTENSION_KEYS = [
  "argument-hint",
  "user-invocable",
  "disable-model-invocation",
  "disallowed-tools",
  "context",
  "agent",
  "model",
];
const ALLOWED_KEYS = new Set([...SPEC_KEYS, ...CLIENT_EXTENSION_KEYS]);

function readUtf8(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function countLines(text) {
  if (text.length === 0) {
    return 0;
  }
  const lines = text.split(/\r\n|\n|\r/);
  return lines[lines.length - 1] === "" ? lines.length - 1 : lines.length;
}

function longestLine(text) {
  return text.split(/\r\n|\n|\r/).reduce((longest, line) => Math.max(longest, line.length), 0);
}

function toPosix(filePath) {
  return filePath.split(path.sep).join("/");
}

function parseFrontmatter(text) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text);
  if (!match) {
    return { data: undefined, body: text, error: "missing YAML frontmatter" };
  }
  try {
    const data = YAML.parse(match[1]) ?? {};
    if (!data || typeof data !== "object" || Array.isArray(data)) {
      return { data: undefined, body: "", error: "frontmatter must be a mapping" };
    }
    return { data, body: text.slice(match[0].length), error: undefined };
  } catch (error) {
    return { data: undefined, body: "", error: `invalid YAML frontmatter: ${error.message}` };
  }
}

function listSkillDirectories(skillsDir) {
  if (!fs.existsSync(skillsDir)) {
    return [];
  }
  return fs
    .readdirSync(skillsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right, "en"));
}

function walk(directory) {
  if (!fs.existsSync(directory)) {
    return [];
  }
  const results = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const full = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      results.push(...walk(full));
    } else if (entry.isFile()) {
      results.push(full);
    }
  }
  return results;
}

// Directories the Agent Skills spec sanctions for bundled resources. They are enumerated but never
// read: an asset may be binary, and the spec sets no line limit on either.
const RESOURCE_DIRECTORIES = ["scripts", "assets"];

function buildManifest() {
  const { root, skillsDir } = layout();
  const skills = [];
  for (const name of listSkillDirectories(skillsDir)) {
    const directory = path.join(skillsDir, name);
    const skillFile = path.join(directory, "SKILL.md");
    const record = {
      name,
      directory: `.llm/skills/${name}`,
      path: `.llm/skills/${name}/SKILL.md`,
      exists: fs.existsSync(skillFile),
      description: "",
      metadata: {},
      license: undefined,
      compatibility: undefined,
      allowedTools: undefined,
      lineCount: 0,
      references: [],
      resources: [],
      errors: [],
    };
    if (!record.exists) {
      record.errors.push("missing SKILL.md");
      skills.push(record);
      continue;
    }
    const text = readUtf8(skillFile);
    record.lineCount = countLines(text);
    const { data, error } = parseFrontmatter(text);
    if (error) {
      record.errors.push(error);
    } else {
      record.frontmatter = data;
      record.description = typeof data.description === "string" ? data.description.trim() : "";
      record.metadata = data.metadata && typeof data.metadata === "object" ? data.metadata : {};
      record.license = data.license;
      record.compatibility = data.compatibility;
      record.allowedTools = data["allowed-tools"];
    }
    record.references = walk(path.join(directory, "references"))
      .map((file) => ({
        path: toPosix(path.relative(root, file)),
        lineCount: countLines(readUtf8(file)),
      }))
      .sort((left, right) => left.path.localeCompare(right.path, "en"));
    record.resources = RESOURCE_DIRECTORIES.flatMap((resourceDirectory) =>
      walk(path.join(directory, resourceDirectory)).map((file) => toPosix(path.relative(root, file)))
    ).sort((left, right) => left.localeCompare(right, "en"));
    skills.push(record);
  }
  return { skills };
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validateFrontmatter(skill, issues, warnings) {
  const add = (message) => issues.push({ path: skill.path, message });
  const data = skill.frontmatter;
  if (!data) {
    return;
  }
  for (const key of REQUIRED_KEYS) {
    if (typeof data[key] !== "string" || data[key].trim() === "") {
      add(`missing required frontmatter field: ${key}`);
    }
  }
  if (typeof data.name === "string") {
    if (data.name.length > 64 || !NAME_PATTERN.test(data.name)) {
      add(
        `name "${data.name}" must be 1-64 lowercase alphanumeric characters and single hyphens, ` +
          "with no leading, trailing, or consecutive hyphens"
      );
    }
    if (data.name !== skill.name) {
      add(`name "${data.name}" must match the directory name "${skill.name}"`);
    }
  }
  if (typeof data.description === "string") {
    if (data.description.length > 1024) {
      add(`description is ${data.description.length} characters (max 1024)`);
    }
    // A newline would break the row this description is rendered into in `.llm/index.md`, and the
    // description is a one-line summary by construction.
    if (/[\r\n]/.test(data.description)) {
      add("description must be a single line; it contains a newline");
    }
  }
  if (data.compatibility !== undefined) {
    if (typeof data.compatibility !== "string") {
      add("compatibility must be a string");
    } else if (data.compatibility.length < 1 || data.compatibility.length > 500) {
      add(`compatibility is ${data.compatibility.length} characters (must be 1-500)`);
    }
  }
  if (data.license !== undefined && typeof data.license !== "string") {
    add("license must be a string");
  }
  // The spec types `allowed-tools` as a space-separated string, not a YAML list.
  if (data["allowed-tools"] !== undefined && typeof data["allowed-tools"] !== "string") {
    add("allowed-tools must be a space-separated string");
  }
  if (data.metadata !== undefined) {
    if (typeof data.metadata !== "object" || data.metadata === null || Array.isArray(data.metadata)) {
      add("metadata must be a mapping");
    } else {
      // The spec types metadata as a map of string keys to string values.
      for (const [key, value] of Object.entries(data.metadata)) {
        if (typeof value !== "string") {
          add(`metadata.${key} must be a string, not ${Array.isArray(value) ? "array" : typeof value}`);
        }
      }
    }
  }
  for (const key of Object.keys(data)) {
    if (!ALLOWED_KEYS.has(key)) {
      // A warning, not an issue: the spec nowhere forbids extra fields, and client extensions are
      // still moving, so a newly documented field must not block every PR in the repository.
      warnings.push({
        path: skill.path,
        message: `unknown frontmatter key "${key}"; repository-specific fields belong under metadata`,
      });
    }
  }
}

function validateLineLimits(issues, warnings) {
  const { root, llmDir, contextFile } = layout();
  for (const skill of buildManifest().skills) {
    if (skill.lineCount > LIMITS.skillFail) {
      issues.push({
        path: skill.path,
        message: `${skill.lineCount} lines (max ${LIMITS.skillFail}); move detail into references/`,
      });
    } else if (skill.lineCount > LIMITS.skillWarn) {
      warnings.push({
        path: skill.path,
        message: `${skill.lineCount} lines (target ${LIMITS.skillWarn})`,
      });
    }
    for (const reference of skill.references) {
      if (reference.lineCount > LIMITS.referenceFail) {
        issues.push({
          path: reference.path,
          message: `${reference.lineCount} lines (max ${LIMITS.referenceFail})`,
        });
      }
    }
  }

  for (const file of walk(llmDir).filter((candidate) => candidate.endsWith(".md"))) {
    const text = readUtf8(file);
    const relative = toPosix(path.relative(root, file));
    const longest = longestLine(text);
    if (longest > LIMITS.lineLength) {
      issues.push({ path: relative, message: `longest line is ${longest} characters (max ${LIMITS.lineLength})` });
    }
  }

  if (fs.existsSync(contextFile)) {
    const contextLines = countLines(readUtf8(contextFile));
    if (contextLines > LIMITS.contextFail) {
      issues.push({ path: ".llm/context.md", message: `${contextLines} lines (max ${LIMITS.contextFail})` });
    }
  } else {
    issues.push({ path: ".llm/context.md", message: "missing" });
  }
}

function validate() {
  const manifest = buildManifest();
  const issues = [];
  const warnings = [];

  if (manifest.skills.length === 0) {
    issues.push({ path: ".llm/skills", message: "no skills found" });
  }
  for (const skill of manifest.skills) {
    for (const error of skill.errors) {
      issues.push({ path: skill.path, message: error });
    }
    validateFrontmatter(skill, issues, warnings);
  }

  const descriptions = new Map();
  for (const skill of manifest.skills) {
    if (!skill.description) {
      continue;
    }
    const key = skill.description.toLowerCase();
    if (descriptions.has(key)) {
      issues.push({
        path: skill.path,
        message: `description is identical to ${descriptions.get(key)}; agents match on description alone`,
      });
    }
    descriptions.set(key, skill.name);
  }

  validateLineLimits(issues, warnings);
  return { manifest, issues, warnings };
}

// ---------------------------------------------------------------------------
// Generated artifacts
// ---------------------------------------------------------------------------

function renderIndexJson(manifest) {
  const skills = manifest.skills.map((skill) => ({
    name: skill.name,
    path: skill.path,
    description: skill.description,
    metadata: skill.metadata,
    lineCount: skill.lineCount,
    references: skill.references.map((reference) => reference.path),
  }));
  return `${JSON.stringify({ skillCount: skills.length, skills }, null, 2)}\n`;
}

function renderIndexMarkdown(manifest) {
  const lines = [
    "# Skill Index",
    "",
    `<!-- ${GENERATED_MARKER}. Do not edit by hand. -->`,
    "",
    `${manifest.skills.length} skills. Each is an [Agent Skills](https://agentskills.io/specification)`,
    "directory: `SKILL.md` holds the instructions, `references/` holds supporting detail loaded on demand.",
    "",
    "| Skill | References | Description |",
    "| --- | --- | --- |",
  ];
  for (const skill of manifest.skills) {
    const description = skill.description.replace(/\|/g, "\\|");
    lines.push(`| [${skill.name}](./skills/${skill.name}/SKILL.md) | ${skill.references.length} | ${description} |`);
  }
  // No trailing blank entry: the single newline below is the file's only line terminator, which is
  // what markdownlint MD012 expects at end of file.
  return `${lines.join("\n")}\n`;
}

function renderRegistryBlock(manifest) {
  return [
    BLOCK_START,
    "",
    `<!-- ${GENERATED_MARKER}. Do not edit by hand. -->`,
    "",
    `${manifest.skills.length} skills are registered. See [the skill index](./index.md) for the full table.`,
    "",
    manifest.skills.map((skill) => `\`${skill.name}\``).join(", "),
    "",
    BLOCK_END,
  ].join("\n");
}

function replaceRegistryBlock(text, block) {
  const starts = text.split(BLOCK_START).length - 1;
  const ends = text.split(BLOCK_END).length - 1;
  if (starts !== 1 || ends !== 1) {
    throw new Error(
      `.llm/context.md must contain exactly one ${BLOCK_START} / ${BLOCK_END} pair (found ${starts} and ${ends})`
    );
  }
  const pattern = new RegExp(`${BLOCK_START}[\\s\\S]*?${BLOCK_END}`, "m");
  return text.replace(pattern, block);
}

function mirrorContent(skill) {
  // Carry every discovery field the source declares. A mirror that dropped `allowed-tools`,
  // `license`, or `compatibility` would make what Claude Code and Codex load differ from source.
  const fields = { name: skill.name, description: skill.description };
  if (skill.license !== undefined) {
    fields.license = skill.license;
  }
  if (skill.compatibility !== undefined) {
    fields.compatibility = skill.compatibility;
  }
  if (skill.allowedTools !== undefined) {
    fields["allowed-tools"] = skill.allowedTools;
  }
  const frontmatter = YAML.stringify(fields).trimEnd();
  return [
    "---",
    frontmatter,
    "---",
    "",
    `<!-- ${GENERATED_MARKER}. Do not edit by hand. -->`,
    "",
    `Canonical instructions: [\`.llm/skills/${skill.name}/SKILL.md\`](../../../.llm/skills/${skill.name}/SKILL.md)`,
    "",
    "Read that file and follow it. Supporting detail is in the sibling `references/` directory.",
    "",
  ].join("\n");
}

function expectedArtifacts(manifest) {
  const { contextFile, indexJson, indexMd, mirrorRoots } = layout();
  const artifacts = new Map();
  artifacts.set(indexJson, renderIndexJson(manifest));
  artifacts.set(indexMd, renderIndexMarkdown(manifest));
  artifacts.set(contextFile, replaceRegistryBlock(readUtf8(contextFile), renderRegistryBlock(manifest)));
  for (const root of mirrorRoots) {
    for (const skill of manifest.skills) {
      artifacts.set(path.join(root, skill.name, "SKILL.md"), mirrorContent(skill));
    }
  }
  return artifacts;
}

/**
 * Previously generated mirror files that are no longer expected, so a renamed skill cannot linger.
 * Scoped to files carrying the generated marker: `.claude/skills/` is also the standard location
 * for a contributor's own hand-authored project skill, and reaping one would destroy their work.
 */
function staleMirrors(expected) {
  const stale = [];
  for (const root of layout().mirrorRoots) {
    for (const file of walk(root)) {
      if (expected.has(file)) {
        continue;
      }
      if (readUtf8(file).includes(GENERATED_MARKER)) {
        stale.push(file);
      }
    }
  }
  return stale;
}

/** Remove directories left empty under the mirror roots, bottom-up, after a rename or removal. */
function pruneEmptyDirectories(directory) {
  if (!fs.existsSync(directory)) {
    return true;
  }
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      pruneEmptyDirectories(path.join(directory, entry.name));
    }
  }
  if (fs.readdirSync(directory).length > 0) {
    return false;
  }
  fs.rmdirSync(directory);
  return true;
}

function writeArtifacts(manifest) {
  const { root: repoRoot, mirrorRoots } = layout();
  const expected = expectedArtifacts(manifest);
  const changed = [];
  for (const [filePath, content] of expected) {
    const current = fs.existsSync(filePath) ? readUtf8(filePath) : undefined;
    if (current === content) {
      continue;
    }
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, "utf8");
    changed.push(toPosix(path.relative(repoRoot, filePath)));
  }
  for (const filePath of staleMirrors(expected)) {
    fs.rmSync(filePath, { force: true });
    changed.push(`removed ${toPosix(path.relative(repoRoot, filePath))}`);
  }
  for (const root of mirrorRoots) {
    if (!fs.existsSync(root)) {
      continue;
    }
    for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        pruneEmptyDirectories(path.join(root, entry.name));
      }
    }
  }
  return changed;
}

function artifactDrifts(manifest) {
  const { root } = layout();
  const expected = expectedArtifacts(manifest);
  const drifts = [];
  for (const [filePath, content] of expected) {
    const relative = toPosix(path.relative(root, filePath));
    if (!fs.existsSync(filePath)) {
      drifts.push({ path: relative, message: "missing generated file" });
    } else if (readUtf8(filePath).replace(/\r\n/g, "\n") !== content.replace(/\r\n/g, "\n")) {
      drifts.push({ path: relative, message: "generated file is stale" });
    }
  }
  for (const filePath of staleMirrors(expected)) {
    drifts.push({ path: toPosix(path.relative(root, filePath)), message: "mirror has no matching skill" });
  }
  return drifts;
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

function report(issues, warnings) {
  for (const warning of warnings) {
    console.warn(`warning: ${warning.path}: ${warning.message}`);
  }
  if (issues.length === 0) {
    return true;
  }
  console.error(`.llm harness validation failed with ${issues.length} issue(s):`);
  for (const issue of issues) {
    console.error(`- ${issue.path}: ${issue.message}`);
  }
  return false;
}

function main(argv) {
  const command = argv[0] ?? "check";
  if (!["index", "validate", "check"].includes(command)) {
    throw new Error(`Unknown command: ${command}. Expected index, validate, or check.`);
  }

  const { manifest, issues, warnings } = validate();
  if (issues.length > 0) {
    report(issues, warnings);
    process.exitCode = 1;
    return;
  }

  if (command === "index") {
    const changed = writeArtifacts(manifest);
    report([], warnings);
    console.log(
      changed.length > 0
        ? `.llm harness: regenerated ${changed.length} artifact(s):\n${changed.map((c) => `  ${c}`).join("\n")}`
        : ".llm harness: generated artifacts already current."
    );
    return;
  }

  const drifts = command === "check" ? artifactDrifts(manifest) : [];
  if (drifts.length > 0) {
    report(
      drifts.map((drift) => ({ ...drift, message: `${drift.message}; run \`npm run llm:index\`` })),
      warnings
    );
    process.exitCode = 1;
    return;
  }

  report([], warnings);
  console.log(
    `.llm harness: ${manifest.skills.length} skills valid` +
      (command === "check" ? ", generated artifacts current." : ".")
  );
}

if (require.main === module) {
  try {
    main(process.argv.slice(2));
  } catch (error) {
    console.error(`.llm harness failed: ${error.message}`);
    process.exitCode = 1;
  }
}

module.exports = {
  GENERATED_MARKER,
  LIMITS,
  NAME_PATTERN,
  artifactDrifts,
  buildManifest,
  countLines,
  expectedArtifacts,
  main,
  mirrorContent,
  parseFrontmatter,
  renderIndexJson,
  renderIndexMarkdown,
  replaceRegistryBlock,
  staleMirrors,
  validate,
  writeArtifacts,
};
