"use strict";

const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const childProcess = require("node:child_process");
const cases = require("./transform-cases.json");
const { walkFiles } = require("../../lib/repo-files.js");
const {
  isExternalLink,
  docsPathToWikiPage,
  findMarkdownLinks,
  CodeBlockTracker,
  transformLine,
  transformFile,
  processAllFiles,
  gitBlobId,
  LEGACY_WIKI_COMMIT
} = require("../transform-docs-to-wiki.js");

function createFixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "dxm-wiki-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  return { root, docsDir: path.join(root, "docs"), wikiDir: path.join(root, "wiki") };
}

function writeFixture(root, relativePath, content) {
  const filePath = path.join(root, relativePath);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

function snapshotTree(root) {
  return walkFiles(root)
    .sort()
    .map((file) => [path.relative(root, file), fs.readFileSync(file).toString("base64")]);
}

function writeOwnership(wikiDir, pages, images) {
  const content = JSON.stringify({ version: 1, pages, images });
  writeFixture(wikiDir, ".dxmessaging-generated-files.json", content);
}

test("Markdown parsing and transforms preserve supported syntax", () => {
  for (const [expected, hrefValues] of cases.externalLinks)
    for (const href of hrefValues) assert.equal(isExternalLink(href), expected, href);
  for (const [input, expected] of cases.wikiPages)
    assert.equal(docsPathToWikiPage(input), expected, input);
  for (const [lines, expected] of cases.fences) {
    const tracker = new CodeBlockTracker();
    const actual = lines.map((line) => tracker.processLine(line));
    assert.deepEqual(actual, expected, lines.join(" / "));
  }
  const links = findMarkdownLinks("[one](a.md) and ![[nested]](image_(v2).png)");
  assert.deepEqual(
    links.map(({ text, href, isImage }) => [text, href, isImage]),
    cases.parsedLinks,
    "parsed links"
  );
  assert.equal(findMarkdownLinks("No links and \\[escaped\\](file.md)").length, 0, "escaped link");
  for (const line of cases.ignoredCode) assert.equal(findMarkdownLinks(line).length, 0, line);
  for (const line of cases.unmatchedCode) assert.equal(findMarkdownLinks(line).length, 1, line);
  assert.equal(findMarkdownLinks("``code`` then [real](page.md)")[0].href, "page.md", "real link");
  for (const [href, currentFile, target] of cases.relativeLinks) {
    assert.equal(transformLine(`[Label](${href})`, currentFile), `[[${target}|Label]]`, href);
  }
  for (const [input, expected] of cases.lineTransforms)
    assert.equal(transformLine(input, "index.md"), expected, input);
  const content = "[before](a.md)\r```\r[inside](b.md)\r```\r[after](c.md)\r";
  const result = transformFile(content, "index.md");
  assert.equal(result, "[[A|before]]\n```\n[inside](b.md)\n```\n[[C|after]]\n", "transformed file");
  assert.equal(transformFile("", "index.md"), "", "empty file");
});

test("processAllFiles reconciles outputs, preserves wiki files, and is byte-idempotent", (t) => {
  const { root, docsDir, wikiDir } = createFixture(t);
  const readmePath = path.join(root, "missing-readme.md");
  writeFixture(docsDir, "index.md", "# Home\n");
  writeFixture(docsDir, "guides/old-name.md", "old bytes\n");
  writeFixture(docsDir, "images/current.png", "current-image");
  writeFixture(wikiDir, "Stale.md", "stale page");
  writeFixture(wikiDir, "wiki-images/stale.png", "stale image");
  writeOwnership(wikiDir, ["Stale.md"], ["stale.png"]);
  const preserved = new Map(cases.protectedFiles);
  for (const [file, content] of preserved) writeFixture(wikiDir, file, content);
  const report = processAllFiles(wikiDir, docsDir, readmePath);
  assert.equal(fs.existsSync(path.join(wikiDir, "Stale.md")), false, "stale page");
  assert.equal(fs.existsSync(path.join(wikiDir, "wiki-images/stale.png")), false, "stale image");
  assert.equal(report.generatedImages.has("current.png"), true, "current image");
  for (const [file, expected] of preserved)
    assert.equal(fs.readFileSync(path.join(wikiDir, file), "utf8"), expected, file);
  fs.renameSync(path.join(docsDir, "guides/old-name.md"), path.join(docsDir, "guides/new-name.md"));
  processAllFiles(wikiDir, docsDir, readmePath);
  const expected = snapshotTree(wikiDir);
  processAllFiles(wikiDir, docsDir, readmePath);
  assert.equal(fs.existsSync(path.join(wikiDir, "Guides-Old-Name.md")), false, "old page");
  assert.deepEqual(snapshotTree(wikiDir), expected, "second generation inventory and bytes");
});

test("final manifest-less snapshot adopts only byte-matching deployed outputs", (t) => {
  assert.equal(LEGACY_WIKI_COMMIT, "64d016d061e3581ae93032ea96c249b401330b7c");
  const { root, docsDir, wikiDir } = createFixture(t);
  const content = "legacy generated bytes";
  const name = "Architecture-Performance.md";
  writeFixture(docsDir, "architecture/performance.md", "current generated bytes");
  writeFixture(root, "README.md", "[Relative](docs/architecture/performance.md)\n");
  writeFixture(wikiDir, name, content);
  writeFixture(wikiDir, "Manual.md", content);
  writeFixture(wikiDir, ".git/HEAD", "trusted tree fixture");
  t.mock.method(childProcess, "execFileSync", (command, args) => {
    assert.deepEqual([command, ...args], ["git", "ls-tree", "-r", "-z", LEGACY_WIKI_COMMIT]);
    return `100644 blob ${gitBlobId(Buffer.from(content))}\t${name}\0`;
  });
  processAllFiles(wikiDir, docsDir, path.join(root, "README.md"));
  assert.equal(fs.readFileSync(path.join(wikiDir, name), "utf8"), "current generated bytes");
  assert.equal(fs.readFileSync(path.join(wikiDir, "Manual.md"), "utf8"), content, "manual page");
  assert.equal(
    fs.readFileSync(path.join(wikiDir, "Home.md"), "utf8"),
    "[[Architecture-Performance|Relative]]\n",
    "README links"
  );
});

test("generation fails before mutation on page, image, and manual-output collisions", (t) => {
  for (const name of ["page", "image", "manual"]) {
    const { root, docsDir, wikiDir } = createFixture(t);
    writeFixture(docsDir, "index.md", "# Home\n");
    writeFixture(wikiDir, "Keep.txt", "keep");
    for (const [file, content] of cases.collisionFiles[name]) writeFixture(root, file, content);
    const before = snapshotTree(wikiDir);
    assert.throws(() => processAllFiles(wikiDir, docsDir), /collision|wiki-owned/, name);
    assert.deepEqual(snapshotTree(wikiDir), before, `${name} failure must not mutate wiki`);
  }
});

test("missing and partial source enumeration fail before reconciliation", (t) => {
  const { root, docsDir, wikiDir } = createFixture(t);
  writeFixture(wikiDir, "Owned.md", "owned");
  writeOwnership(wikiDir, ["Owned.md"], []);
  const before = snapshotTree(wikiDir);
  assert.throws(
    () => processAllFiles(wikiDir, path.join(root, "missing")),
    /enumerate/,
    "missing docs"
  );
  assert.deepEqual(snapshotTree(wikiDir), before, "missing source must not reconcile");
  const blockedDir = path.join(docsDir, "blocked");
  writeFixture(docsDir, "index.md", "# Home\n");
  writeFixture(blockedDir, "page.md", "blocked");
  const original = fs.readdirSync;
  const mocked = t.mock.method(fs, "readdirSync", (directory, options) => {
    if (path.resolve(directory) === path.resolve(blockedDir)) throw new Error("permission denied");
    return original(directory, options);
  });
  assert.throws(() => processAllFiles(wikiDir, docsDir), /permission denied/, "partial docs");
  mocked.mock.restore();
  assert.deepEqual(snapshotTree(wikiDir), before, "partial source must not reconcile");
});

test("managed symlinks cannot write or delete outside the wiki", (t) => {
  if (process.platform === "win32") return t.skip("symlink creation needs elevated privileges");
  for (const [kind, relativePath] of cases.symlinks) {
    const { root, docsDir, wikiDir } = createFixture(t);
    const outside = path.join(root, `${kind}-outside`);
    writeFixture(docsDir, "index.md", "# Home\n");
    writeFixture(outside, "sentinel", "outside bytes");
    if (kind !== "root") fs.mkdirSync(wikiDir, { recursive: true });
    if (kind === "owned") writeOwnership(wikiDir, [relativePath], []);
    const directoryLink = kind === "root" || kind === "images";
    fs.symlinkSync(
      directoryLink ? outside : path.join(outside, "sentinel"),
      relativePath ? path.join(wikiDir, relativePath) : wikiDir,
      directoryLink ? "dir" : "file"
    );
    const before = snapshotTree(outside);
    assert.throws(() => processAllFiles(wikiDir, docsDir), /symbolic link/, kind);
    assert.deepEqual(snapshotTree(outside), before, `${kind} must not escape the wiki`);
  }
});

test("current docs generation has no unresolved internal wiki targets", (t) => {
  const { wikiDir } = createFixture(t);
  const report = processAllFiles(wikiDir);
  const invalid = [];
  for (const page of report.generatedPages) {
    const content = fs.readFileSync(path.join(wikiDir, page), "utf8");
    if (content.includes("[[..")) invalid.push(`${page}: malformed relative target`);
    for (const match of content.matchAll(/\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]/g)) {
      if (!report.generatedPages.has(`${match[1]}.md`)) invalid.push(`${page}: ${match[1]}`);
    }
  }
  assert.deepEqual(invalid, [], `invalid wiki targets:\n${invalid.join("\n")}`);
});
